name: Wiki Sync

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki-sync.yml'

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki/
          strategy: clone
